template:
    # kiosk mode
    # the folowing parameters can be changed
    # 250 W is the base comsumtion
    # 3500 W is the solar production to charge at 12 A
    # 12 A is the maximum current to charge
    - sensor:
      - name: "Charging Amps Kiosk"
        unit_of_measurement: "A"
        state: >
          {% set  power = states('sensor.XXXXXXXXXX_realtime_power') | float %}
          {% set m=(12/(3500 - 250)) %}
          {% set b= -m*250 %}
          {% set  amps = ((power *1000 * m) + b) | round(0) %} 
            {% if  amps < 0 %}
            {% set amps = 0 %}
            {% endif %}
            {% if amps > 12 %}
            {% set amps = 12 %}
            {% endif %}
            {{ amps }}  
switch:
  - platform: template
    switches:
      followthesun:
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.followthesun_yes
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.followthesun_no
